import { useState } from "react";
import Head from "next/head";
import Image from "next/image";
import styles from "../styles/Home.module.css";

const TestComponent = ({ session, item }) => {
  const editable = (session, item) => {
    console.log("Session %s", session);
    console.log("Item %s", item);
    return { canDo: Boolean(session && item) };
  };

  const [editorStatus, setEditorStatus] = useState({
    canEdit: editable(session, item),
    canSave: editable(session, item),
  });

  return (
    <>
      <div>Session: {session}</div>
      <div>Item: {item}</div>
      <div>State: {JSON.stringify(editorStatus)}</div>
    </>
  );
};

const Controller = () => {
  const [session, setSession] = useState(0);
  const [item, setItem] = useState(0);

  return (
    <>
      <button onClick={() => setSession(session + 1)}>Session</button>
      <button onClick={() => setItem(item + 2)}>Test</button>
      <TestComponent session={session} item={item} />
    </>
  );
};

export default function Home() {
  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <Controller />
      </main>
    </div>
  );
}
